// 自作8bitアイコンのドットデータ（16x16）。1文字 = 1ドット。
// "." は透明、それ以外は PALETTE の色。描画は PixelIcon.tsx。

export const PALETTE: Record<string, string> = {
  k: "#1a1626", // ふちどり（public/en のスプライトと同じ濃紺）
  w: "#f4f0ff",
  y: "#ffd866",
  o: "#c9962e",
  r: "#ff6b6b",
  b: "#6ec6ff",
  p: "#c084fc",
  P: "#8b5fd1",
  g: "#8be08b",
  G: "#3f9e5a",
  s: "#9aa0b5",
  d: "#5a5f78",
  n: "#8a5a3c",
  z: "#cd7f32",
  Z: "#8f5520",
};

/** 色だけ差し替えた派生アイコンを作る（メダルの金銀銅など） */
const recolor = (rows: readonly string[], map: Record<string, string>): string[] =>
  rows.map((row) => [...row].map((ch) => map[ch] ?? ch).join(""));

const BASE = {
  // あそびかた: まなびのしょ
  book: [
    "................",
    "................",
    ".kkkkkk..kkkkkk.",
    "kwwwwwwkkwwwwwwk",
    "kwddddwkkwddddwk",
    "kwwwwwwkkwwwwwwk",
    "kwddddwkkwdddwwk",
    "kwwwwwwkkwwwwwwk",
    "kwdddwwkkwddddwk",
    "kwwwwwwkkwwwwwwk",
    "kyyyyyyyyyyyyyyk",
    "kooooookkooooook",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ],
  // ぼうけんをはじめる: しろ
  castle: [
    ".......kkkk.....",
    ".......krrrk....",
    ".......krrk.....",
    ".......kk.......",
    "kkk.kkkkkkkk.kkk",
    "kskkkskkkkskkksk",
    "kssssssssssssssk",
    "kssssssssssssssk",
    "kssdssssssssdssk",
    "kssdssssssssdssk",
    "ksssskkkkkkssssk",
    "kssssknnnnkssssk",
    "kssssknnonkssssk",
    "kssssknnnnkssssk",
    "kkkkkkkkkkkkkkkk",
    "................",
  ],
  // あいことばでくわわる: かぎ
  key: [
    "................",
    "................",
    "................",
    "..kkkk..........",
    ".kyyyyk.........",
    "kyykkyyk........",
    "kyk..kykkkkkkkkk",
    "kyk..kyyyyyyyyyk",
    "kyk..kyoooyooyok",
    "kyykkyykkykkykk.",
    ".kyyyyk.kyk.kyk.",
    "..kkkk...k...k..",
    "................",
    "................",
    "................",
    "................",
  ],
  // ひとりでしゅぎょう: つるぎ
  sword: [
    "............kkkk",
    "...........kwwwk",
    "..........kwswwk",
    ".........kwswwk.",
    "........kwswwk..",
    ".......kwswwk...",
    "......kwswwk....",
    ".kk..kwswwk.....",
    ".kykkwswwk......",
    "..kyyswwk.......",
    "..kkyyyk........",
    ".knnkyyyk.......",
    "knnk.kkyk.......",
    "kok....kk.......",
    "kk..............",
    "................",
  ],
  // うぉーろーど: どくろ
  skull: [
    "....kkkkkkkk....",
    "..kkwwwwwwwwkk..",
    ".kwwwwwwwwwwwwk.",
    ".kwwwwwwwwwwwwk.",
    "kwwwwwwwwwwwwwwk",
    "kwwkkkwwwwkkkwwk",
    "kwwkpkwwwwkpkwwk",
    "kwwkkkwwwwkkkwwk",
    "kwwwwwwkkwwwwwwk",
    ".kwwwwwkkwwwwwk.",
    "..kkwwwwwwwwkk..",
    "...kwkwkkwkwk...",
    "...kwkwkkwkwk...",
    "...kwwwwwwwwk...",
    "....kkkkkkkk....",
    "................",
  ],
  // たたかいをみる: め
  eye: [
    "................",
    "................",
    ".....kkkkkk.....",
    "...kkwwwwwwkk...",
    "..kwwwkkkkwwwk..",
    ".kwwwkbbbbkwwwk.",
    "kwwwkbbkkwbkwwwk",
    "kwwwkbkkkkbkwwwk",
    "kwwwkbkkkkbkwwwk",
    ".kwwwkbbbbkwwwk.",
    "..kwwwkkkkwwwk..",
    "...kkwwwwwwkk...",
    ".....kkkkkk.....",
    "................",
    "................",
    "................",
  ],
  // でんせつのきろく: トロフィー
  trophy: [
    "..kkkkkkkkkkkk..",
    ".kkyyyyyyyyyykk.",
    "kykkywyyyyyykkyk",
    "kyk.kywyyyyk.kyk",
    "kyk.kywyyyyk.kyk",
    ".kykkyyyyyykkyk.",
    "..kkkyyyyyykkk..",
    "....kyyyyyyk....",
    ".....kyyyyk.....",
    "......kyok......",
    "......kyok......",
    ".....kkyokk.....",
    "....kyyyyyyk....",
    "....kooooook....",
    "....kkkkkkkk....",
    "................",
  ],
  // こうげき・アタッカー: まじわるつるぎ
  swords: [
    "kk............kk",
    "kwk..........kwk",
    "kwwk........kwwk",
    ".kwwk......kwwk.",
    "..kwwk....kwwk..",
    "...kwwk..kwwk...",
    "....kwwkkwwk....",
    ".....kwwwwk.....",
    ".....kwwwwk.....",
    "....kwwkkwwk....",
    ".k.kwwk..kwwk.k.",
    "kykwwk....kwwkyk",
    ".kyyk......kyyk.",
    ".kyyyk....kyyyk.",
    "knk.kyk..kyk.knk",
    "kk...k....k...kk",
  ],
  // かいふく・ヒーラー
  heart: [
    "................",
    "..kkkk....kkkk..",
    ".kggggk..kggggk.",
    "kgwwgggkkgggggGk",
    "kgwggggggggggGGk",
    "kggggggggggggGGk",
    "kggggggggggggGGk",
    ".kggggggggggGGk.",
    "..kggggggggGGk..",
    "...kggggggGGk...",
    "....kggggGGk....",
    ".....kggGGk.....",
    "......kGGk......",
    ".......kk.......",
    "................",
    "................",
  ],
  // ぼうぎょ・タンク
  shield: [
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kbbbbbyybbbbbk.",
    ".kbbbbbyybbbbbk.",
    ".kbbbbbyybbbbbk.",
    ".kyyyyyyyyyyyyk.",
    ".kyyyyyyyyyyyyk.",
    ".kbbbbbyybbbbbk.",
    ".kbbbbbyybbbbbk.",
    "..kbbbbyybbbbk..",
    "..kbbbbyybbbbk..",
    "...kbbbyybbbk...",
    "....kbbyybbk....",
    ".....kbyybk.....",
    "......kkkk......",
    "................",
  ],
  // おうえん・バッファー
  trumpet: [
    "................",
    "................",
    "................",
    "....k.k.k...kkk.",
    "...kykykyk.kyyk.",
    ".kk.kykyk.kyyyk.",
    "kyykkykykkyyyyk.",
    "kyyyyyyyyyyyyyk.",
    "kyykkkkkkkyyyyk.",
    ".kk.kyyyk.kyyyk.",
    "....kykyk..kyyk.",
    "....kyyyk...kkk.",
    ".....kkk........",
    "................",
    "................",
    "................",
  ],
  // ばーさーかー
  axe: [
    "................",
    ".....kk..kkk....",
    "....knnkkssskk..",
    "....knnkssssssk.",
    "....knnksssswsk.",
    "....knnkssssswk.",
    "....knnkssssswk.",
    "....knnksssswsk.",
    "....knnkssssssk.",
    "....knnkkssskk..",
    "....knnk.kkk....",
    "....knnk........",
    "....knnk........",
    "....knnk........",
    "....kkkk........",
    "................",
  ],
  // 回復の杖
  staff: [
    "......kkkk......",
    ".....kppppk.....",
    "....kpwppppk....",
    "....kpppppPk....",
    ".....kppPPk.....",
    "....kykkkkyk....",
    ".....kyyyyk.....",
    "......knnk......",
    "......knnk......",
    "......knnk......",
    "......knnk......",
    "......knnk......",
    "......knnk......",
    "......knnk......",
    "......kkkk......",
    "................",
  ],
  // 疾風のブーツ
  boots: [
    "................",
    "....kkkkkk......",
    "....kyyyyk......",
    ".kk.knnnnk......",
    "kwwkknnnnk......",
    ".kwwknnnnk......",
    "..kkknnnnk......",
    "....knnnnk......",
    "....knnnnkkk....",
    "....knnnnnnnkk..",
    "....knnnnnnnnnk.",
    "....knnnnnnnnnk.",
    "....kookkoooook.",
    "....kkkkkkkkkkk.",
    "................",
    "................",
  ],
  // ステージ: PC
  pc: [
    "................",
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kssssssssssssk.",
    ".kskkkkkkkkkksk.",
    ".kskgkkkkkkkksk.",
    ".kskkggkkkkkksk.",
    ".kskkkkkkkkkksk.",
    ".kskkkkkkkkkksk.",
    ".kssssssssssssk.",
    ".kkkkkkkkkkkkkk.",
    "kssssssssssssssk",
    "kswswswswswswssk",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
  ],
  // ITようご: キーボード
  keyboard: [
    "................",
    "................",
    "................",
    "................",
    ".kkkkkkkkkkkkkk.",
    "kssssssssssssssk",
    "kswswswswswswssk",
    "kssssssssssssssk",
    "ksswswswswswsssk",
    "kssssssssssssssk",
    "kswswwwwwwswswsk",
    "kssssssssssssssk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ],
  // ステージ: サーバー
  server: [
    "................",
    "..kkkkkkkkkkkk..",
    "..kssssssssssk..",
    "..ksgsddddddsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "..kssssssssssk..",
    "..ksgsddddddsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "..kssssssssssk..",
    "..ksrsddddddsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
  // ステージ: 障害発生
  siren: [
    "................",
    ".y.....kk.....y.",
    "..y..kkkkkk..y..",
    "....krrrrrrk....",
    "...krrwrrrrrk...",
    "yy.krwrrrrrrk.yy",
    "...krwrrrrrrk...",
    "...krrrrrrrrk...",
    "...krrrrrrrrk...",
    "...krrrrrrrrk...",
    "..kkkkkkkkkkkk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
    "................",
  ],
  warning: [
    "................",
    ".......kk.......",
    "......kyyk......",
    "......kyyk......",
    ".....kyyyyk.....",
    ".....kykkyk.....",
    "....kyykkyyk....",
    "....kyykkyyk....",
    "...kyyykkyyyk...",
    "...kyyykkyyyk...",
    "..kyyyyyyyyyyk..",
    "..kyyyykkyyyyk..",
    ".kyyyyykkyyyyyk.",
    ".kyyyyyyyyyyyyk.",
    ".kkkkkkkkkkkkkk.",
    "................",
  ],
  // ユニゾン・まほう
  sparkle: [
    "................",
    ".....k..........",
    "....kyk....k....",
    "....kyk...kyk...",
    "...kywyk...k....",
    ".kkyywyykk......",
    "kyyywwwyyyk.....",
    ".kkyywyykk......",
    "...kywyk........",
    "....kyk....k....",
    "....kyk...kyk...",
    ".....k...kywyk..",
    "..........kyk...",
    "...........k....",
    "................",
    "................",
  ],
  // そうび: たからばこ
  chest: [
    "................",
    "................",
    "..kkkkkkkkkkkk..",
    ".knnnnnyynnnnnk.",
    "knnnnnnyynnnnnnk",
    "knnnnnnyynnnnnnk",
    "kyyyyyykkyyyyyyk",
    "kkkkkkkyykkkkkkk",
    "knnnnnkyyknnnnnk",
    "knnnnnnkknnnnnnk",
    "knnnnnnnnnnnnnnk",
    "knnnnnnnnnnnnnnk",
    "kooooooooooooook",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
  ],
  // ミス・エラー
  burst: [
    "................",
    ".k.....kk.....k.",
    ".kk...krrk...kk.",
    ".krk..krrk..krk.",
    "..krkkryyrkkrk..",
    "..krryyyyyyrrk..",
    ".kkryywwwwyyrkk.",
    "krryywwwwwwyyrrk",
    "krryywwwwwwyyrrk",
    ".kkryywwwwyyrkk.",
    "..krryyyyyyrrk..",
    "..krkkryyrkkrk..",
    ".krk..krrk..krk.",
    ".kk...krrk...kk.",
    ".k.....kk.....k.",
    "................",
  ],
  // コンボ・いかり
  fire: [
    "................",
    ".......k........",
    "......krk.......",
    "......krrk......",
    ".....krrrk.k....",
    "....krrrrkkrk...",
    "...krryrrrrrk...",
    "..krryyrrryrrk..",
    "..krryyyryyrrk..",
    ".krryyyyyyyrrrk.",
    ".krryywwyyyyrrk.",
    ".krryywwwyyrrrk.",
    "..krryywwyyrrk..",
    "...krryyyyrrk...",
    "....kkkkkkkk....",
    "................",
  ],
  // そせい
  helmet: [
    "................",
    "................",
    "................",
    ".....kkkkkk.....",
    "...kkrrwwrrkk...",
    "..krrrrwwrrrrk..",
    ".krrwwwwwwwwrrk.",
    ".krrwwwwwwwwrrk.",
    ".krrrrrwwrrrrrk.",
    "krrrrrrwwrrrrrrk",
    "kkkkkkkkkkkkkkkk",
    "kssssssssssssssk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ],
  check: [
    "................",
    ".kkkkkkkkkkkkkk.",
    "kGGGGGGGGGGGGGGk",
    "kGGGGGGGGGGGwwGk",
    "kGGGGGGGGGGwwwGk",
    "kGGGGGGGGGwwwGGk",
    "kGGGGGGGGwwwGGGk",
    "kGwwGGGGwwwGGGGk",
    "kGwwwGGwwwGGGGGk",
    "kGGwwwwwwGGGGGGk",
    "kGGGwwwwGGGGGGGk",
    "kGGGGwwGGGGGGGGk",
    "kGGGGGGGGGGGGGGk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
  ],
  // きぜつ
  dizzy: [
    "................",
    "....kkkkkkkk....",
    "..kkyyyyyyyykk..",
    ".kyyyyyyyyyyyyk.",
    ".kykykyyyykykyk.",
    "kyyykyyyyyykyyyk",
    "kyykykyyyykykyyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyykkkkyyyyyk",
    ".kyyykwwwwkyyyk.",
    ".kyyyykkkkyyyyk.",
    "..kkyyyyyyyykk..",
    "....kkkkkkkk....",
    "................",
    "................",
  ],
  // 弱点
  bolt: [
    ".......kkkkkk...",
    "......kyyyyk....",
    ".....kyyyyk.....",
    "....kyyyyk......",
    "...kyyyykkkkk...",
    "..kyyyyyyyyk....",
    "..kkkkkyyyk.....",
    "......kyyk......",
    ".....kyyk.......",
    "....kyyk........",
    "....kyk.........",
    "...kyk..........",
    "...kk...........",
    "................",
    "................",
    "................",
  ],
  question: [
    "................",
    "....kkkkkkkk....",
    "...kwwwwwwwwk...",
    "..kwwkkkkkkwwk..",
    "..kwwk....kwwk..",
    "..kkkk...kwwwk..",
    "........kwwwk...",
    ".......kwwwk....",
    "......kwwwk.....",
    "......kwwk......",
    "......kkkk......",
    "......kwwk......",
    "......kwwk......",
    "......kkkk......",
    "................",
    "................",
  ],
  // クリア: ほし＋かみふぶき
  party: [
    "................",
    "..r.....y....b..",
    ".......kk...p...",
    "..b...kyyk......",
    "......kyyk..r...",
    ".kkkkkyyyykkkkk.",
    ".kyyyyyyyyyyyyk.",
    "..kyyyyyyyyyyk..",
    "...kyyyyyyyyk...",
    "...kyyyyyyyyk...",
    "..kyyyykkyyyyk..",
    "..kyykk..kkyyk..",
    ".kykk......kkyk.",
    ".kk...p..b...kk.",
    "................",
    "................",
  ],
  star: [
    "................",
    "................",
    ".......kk.......",
    "......kyyk......",
    "......kyyk......",
    ".kkkkkyyyykkkkk.",
    ".kyyyyywyyyyyyk.",
    "..kyyywyyyyyyk..",
    "...kyyyyyyyyk...",
    "...kyyyyyyyyk...",
    "..kyyyykkyyyyk..",
    "..kyykk..kkyyk..",
    ".kykk......kkyk.",
    ".kk..........kk.",
    "................",
    "................",
  ],
  target: [
    "................",
    ".....kkkkkk.....",
    "...kkrrrrrrkk...",
    "..krrrwwwwrrrk..",
    ".krrwwwwwwwwrrk.",
    ".krwwwrrrrwwwrk.",
    "krrwwrrrrrrwwrrk",
    "krrwwrrwwrrwwrrk",
    "krrwwrrwwrrwwrrk",
    "krrwwrrrrrrwwrrk",
    ".krwwwrrrrwwwrk.",
    ".krrwwwwwwwwrrk.",
    "..krrrwwwwrrrk..",
    "...kkrrrrrrkk...",
    ".....kkkkkk.....",
    "................",
  ],
  // あきらめる: しろはた
  flag: [
    "................",
    "..kk............",
    "..knkkkkkkkkk...",
    "..knwwwwwwwwwk..",
    "..knwwwwwwwwwk..",
    "..knwwwwwwwwwk..",
    "..knwwwwwwwwwk..",
    "..knwwwwwwwwk...",
    "..knkkkkkkkk....",
    "..knk...........",
    "..knk...........",
    "..knk...........",
    "..knk...........",
    "..knk...........",
    "..kkk...........",
    "................",
  ],
  crown: [
    "................",
    "................",
    "................",
    "kk.....kk.....kk",
    "kyk...kyyk...kyk",
    "kyyk.kyyyyk.kyyk",
    "kyyykyyyyyykyyyk",
    "kyyyyyyyyyyyyyyk",
    "kyryyyybbyyyyryk",
    "kyyyyyybbyyyyyyk",
    "kooooooooooooook",
    "kkkkkkkkkkkkkkkk",
    "................",
    "................",
    "................",
    "................",
  ],
  anger: [
    "................",
    "................",
    "....krk..krk....",
    "....krk..krk....",
    "..kkkrk..krkkk..",
    "..krrrk..krrrk..",
    "..kkkk....kkkk..",
    "................",
    "................",
    "..kkkk....kkkk..",
    "..krrrk..krrrk..",
    "..kkkrk..krkkk..",
    "....krk..krk....",
    "....krk..krk....",
    "................",
    "................",
  ],
  puff: [
    "................",
    "................",
    "................",
    "................",
    "......kkkk......",
    "....kkwwwwkk....",
    "k..kwwwwwwwwk...",
    ".kkkwwwwwwwwwkk.",
    "....kwwwwwwwwwwk",
    "kkk.kwwwwwwwwwwk",
    "....kkwwwwwwwkk.",
    ".kk...kkkkkkk...",
    "................",
    "................",
    "................",
    "................",
  ],
  chain: [
    "................",
    "................",
    "................",
    "................",
    "................",
    ".kkkkk....kkkkk.",
    "ksssssk..ksssssk",
    "kskkkskkkkskkksk",
    "ksk.kssssssk.ksk",
    "kskkkskkkkskkksk",
    "ksssssk..ksssssk",
    ".kkkkk....kkkkk.",
    "................",
    "................",
    "................",
    "................",
  ],
  // じゅんびのやかた
  tent: [
    "................",
    ".......kk.......",
    "......krrk......",
    "......krrk......",
    ".....krrrrk.....",
    ".....krrrrk.....",
    "....krrddrrk....",
    "....krrddrrk....",
    "...krrddddrrk...",
    "...krrddddrrk...",
    "..krrddddddrrk..",
    "..krrddddddrrk..",
    ".kkkkkkkkkkkkkk.",
    "GGGGGGGGGGGGGGGG",
    "................",
    "................",
  ],
  medal: [
    "..kkkk....kkkk..",
    "..kbbk....kbbk..",
    "...kbbk..kbbk...",
    "....kbbkkbbk....",
    ".....kbbbbk.....",
    ".....kkkkkk.....",
    "....kyyyyyyk....",
    "...kyywyyyyyk...",
    "...kywyyyyyok...",
    "...kyyyyyyyok...",
    "...kyyyyyyook...",
    "...kyyyyoooyk...",
    "....kyyyyyyk....",
    ".....kkkkkk.....",
    "................",
    "................",
  ],
  // タイプ数
  numbers: [
    "................",
    "................",
    "................",
    ".kkkkkkkkkkkkkk.",
    "kddddddddddddddk",
    "kddwddwwwdwwwddk",
    "kdwwddddwdddwddk",
    "kddwddwwwdwwwddk",
    "kddwddwddddddwdk",
    "kdwwwdwwwdwwwddk",
    "kddddddddddddddk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
    "................",
  ],
  scroll: [
    "................",
    ".kkkkkkkkkkkkkk.",
    "kooooooooooooook",
    ".kkkkkkkkkkkkkk.",
    "..kwwwwwwwwwwk..",
    "..kwddddddddwk..",
    "..kwwwwwwwwwwk..",
    "..kwddddddwwwk..",
    "..kwwwwwwwwwwk..",
    "..kwdddddddwwk..",
    "..kwwwwwwwwwwk..",
    ".kkkkkkkkkkkkkk.",
    "kooooooooooooook",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
  ],
  lock: [
    "................",
    ".....kkkkkk.....",
    "....kssssssk....",
    "...kssk..kssk...",
    "...kssk..kssk...",
    "...kssk..kssk...",
    "..kkkkkkkkkkkk..",
    "..kyyyyyyyyyyk..",
    "..kyyyykkyyyyk..",
    "..kyyyykkyyyyk..",
    "..kyyyykkyyyyk..",
    "..kyyyyyyyyyyk..",
    "..kooooooooook..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
  apple: [
    "................",
    "........kk......",
    ".......knk.kk...",
    ".......knkkggk..",
    "...kkkkknkkkk...",
    "..krrrrrrrrrrk..",
    ".krrwrrrrrrrrrk.",
    ".krwrrrrrrrrrrk.",
    ".krrrrrrrrrrrrk.",
    ".krrrrrrrrrrrrk.",
    ".krrrrrrrrrrrrk.",
    "..krrrrrrrrrrk..",
    "...krrrrrrrrk...",
    "....kkrrrrkk....",
    "......kkkk......",
    "................",
  ],
  paw: [
    "................",
    "....kk....kk....",
    "...kook..kook...",
    "...kook..kook...",
    ".kk.kk....kk.kk.",
    "kook........kook",
    "kook..kkkk..kook",
    ".kk.kkookkkk.kk.",
    "...kooooooook...",
    "..kooooooooook..",
    "..kooooooooook..",
    "..kooooooooook..",
    "...kooooooook...",
    "....kkkkkkkk....",
    "................",
    "................",
  ],
  tree: [
    ".......kk.......",
    "......kggk......",
    ".....kggggk.....",
    "....kggGgggk....",
    ".....kggggk.....",
    "....kggggggk....",
    "...kggggGgggk...",
    "....kggggggk....",
    "...kggggggggk...",
    "..kggGgggggggk..",
    ".kggggggggGgggk.",
    ".kkkkkknnkkkkkk.",
    "......knnk......",
    "......knnk......",
    "......kkkk......",
    "................",
  ],
  car: [
    "................",
    "................",
    "................",
    "....kkkkkkk.....",
    "...krbbkbbrk....",
    "..krrbbkbbrrk...",
    ".kkrrrrrrrrrrkk.",
    "krrrrrrrrrrrrrrk",
    "kyrrrrrrrrrrrryk",
    "krrkkkrrrrkkkrrk",
    "kkkdsdkkkkdsdkkk",
    "..kdddk..kdddk..",
    "...kkk....kkk...",
    "................",
    "................",
    "................",
  ],
} as const;

export const ICONS = {
  ...BASE,
  medalSilver: recolor(BASE.medal, { y: "s", o: "d" }),
  medalBronze: recolor(BASE.medal, { y: "z", o: "Z" }),
  // インク攻撃のしみ（blur をかけて影として使う）
  heartBlack: recolor(BASE.heart, { g: "d", G: "d", w: "s" }),
} as const;

export type PixelIconName = keyof typeof ICONS;

// 文字列に埋まっている絵文字 → アイコン。ログやフロート文字など「文字列のまま
// 流れてくるもの」は <Px> がこの表で置き換える（RTDB には絵文字のまま載る）。
export const EMOJI_ICON: Record<string, PixelIconName> = {
  "🎓": "book", "🏰": "castle", "🤝": "key", "🗡": "sword", "☠": "skull", "💀": "skull",
  "📺": "eye", "🏆": "trophy", "⚔": "swords", "💚": "heart", "🛡": "shield", "🎺": "trumpet",
  "🪓": "axe", "🪄": "staff", "👢": "boots", "💻": "pc", "⌨": "keyboard", "🗄": "server",
  "🚨": "siren", "⚠": "warning", "✨": "sparkle", "🎁": "chest", "💥": "burst", "🔥": "fire",
  "⛑": "helmet", "✅": "check", "😵": "dizzy", "⚡": "bolt", "❔": "question", "🎉": "party",
  "⭐": "star", "🌟": "star", "🎯": "target", "🏳": "flag", "👑": "crown", "💢": "anger",
  "💨": "puff", "🔗": "chain", "🏕": "tent", "🥇": "medal", "🥈": "medalSilver",
  "🥉": "medalBronze", "🔢": "numbers", "📜": "scroll", "🔒": "lock", "🍎": "apple",
  "🐾": "paw", "🌲": "tree", "🚗": "car", "🖤": "heartBlack",
};
